spring:
  application:
    name: eureka-service
server:
  port: 8302
eureka:
  client:
    registryWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0


#/api/db-service
#/api/stock-service

zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8300
    stock-service:
      path: /stock-service/**
      url: http://localhost:8301
